name: HAMC Server Java with RCON
description: Host a Java Minecraft server on Home Assistant
version: 1.1.7.beta8
slug: hamc-java-rcon
init: false
arch:
  - amd64
  - aarch64
  - armv7
ports:
  25565/tcp: "25565"
  25575/tcp: "25575"
  19132/udp: "19132"
  8123/tcp: "8124"
  8804/tcp: "8804"
ports_description:
  25565/tcp: Minecraft Server Port
  25575/tcp: Minecraft RCON Port
  19132/udp: Geyser (Bedrock) Port
  8123/tcp: DynMap HTTP Port
  8804/tcp: Plan Server statistics HTTP Port
options:
  VERSION: LATEST
  TYPE: PAPER
  SERVER_NAME: "HAMC Java Server"
  MOTD: "Greetings from Home Assistant"
  LEVEL: "World"
  GAMEMODE: creative
  DIFFICULTY: normal
  HARDCORE: false
  MAX_PLAYERS: 20
  WHITELIST: ""
  OPS: ""
  SPAWN_PROTECTION: 0
  PVP: true
  MAX_WORLD_SIZE: 29999984
  ALLOW_NETHER: true
  SEED: ""
  VIEW_DISTANCE: 10
  ONLINE_MODE: true
  MEMORY: 1G
  ANNOUNCE_PLAYER_ACHIEVEMENTS: true
  ENABLE_COMMAND_BLOCK: false
  FORCE_GAMEMODE: false
  MAX_BUILD_HEIGHT: 256
  PAUSE_WHEN_EMPTY_SECONDS: 60
  SPIGET_RESOURCES: "109224"
  INTERNAL_NOTES: "Just some internal notes for you - Spiget 109224 (AutoUpdateViaVersion)"
schema:
  VERSION: str
  TYPE: list(VANILLA|SPIGOT|FABRIC|FORGE|PAPER|QUILT|MAGMA|SPONGEVANILLA|LIMBO|CRUCIBLE)
  SERVER_NAME: str
  MOTD: str
  LEVEL: str
  GAMEMODE: list(survival|creative|adventure|spectator)
  DIFFICULTY: list(peaceful|easy|normal|hard)
  HARDCORE: bool
  MAX_PLAYERS: int
  WHITELIST: str
  OPS: str
  SPAWN_PROTECTION: int
  PVP: bool
  MAX_WORLD_SIZE: int
  ALLOW_NETHER: bool
  SEED: str
  VIEW_DISTANCE: int
  ONLINE_MODE: bool
  MEMORY: str
  ANNOUNCE_PLAYER_ACHIEVEMENTS: bool
  ENABLE_COMMAND_BLOCK: bool
  FORCE_GAMEMODE: bool
  MAX_BUILD_HEIGHT: int
  RCON_PASSWORD: password
  PAUSE_WHEN_EMPTY_SECONDS: int
  SPIGET_RESOURCES: str
  INTERNAL_NOTES: str
map:
  - addons:rw
environment:
  EULA: "TRUE"
  PLUGINS: |
    https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
    https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    https://dev.bukkit.org/projects/worldedit/files/latest
    https://dev.bukkit.org/projects/worldguard/files/latest
    https://dynmap.us/builds/dynmap/Dynmap-3.7-beta-8-spigot.jar
    https://dev.bukkit.org/projects/multiverse-portals/files/latest
    https://github.com/cjburkey01/ClaimChunk/releases/download/0.0.25-FIX3/claimchunk-0.0.25-FIX3-plugin.jar
    https://github.com/Mineduino/Mineduino-spigot/releases/download/1.2.2/mineduino-1.2.2.jar
